/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import javax.swing.JOptionPane;
import controle.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Admin;
import modelo.Cliente;
import modelo.Grupo;
import modelo.Usuario;
/**
 *
 * @author guylh
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    Grupo lista;
    
    
    public TelaLogin() {
        initComponents();
        try {
            lista = ControleArquivo.recuperarGrupo();
        } catch (IOException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAcesso = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabellogo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seja Bem -Vindo");
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonAcesso.setText("Acesso");
        jButtonAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessoActionPerformed(evt);
            }
        });
        jButtonAcesso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAcessoKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonAcesso);
        jButtonAcesso.setBounds(210, 180, 73, 30);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(300, 180, 73, 30);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsuario.setForeground(java.awt.Color.white);
        jLabelUsuario.setText("Usuário:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(190, 90, 70, 17);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSenha.setForeground(java.awt.Color.white);
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(190, 130, 60, 17);

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(260, 80, 110, 30);
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(260, 120, 110, 30);

        jLabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/livraria.png"))); // NOI18N
        getContentPane().add(jLabellogo);
        jLabellogo.setBounds(0, 50, 180, 190);

        jLabelTitulo.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(java.awt.Color.white);
        jLabelTitulo.setText("Sistema de Livraria");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(50, 10, 300, 50);

        jLabelTelaLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.jpg"))); // NOI18N
        jLabelTelaLogin.setText("jLabel1");
        getContentPane().add(jLabelTelaLogin);
        jLabelTelaLogin.setBounds(0, 0, 405, 302);

        setSize(new java.awt.Dimension(405, 302));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessoActionPerformed
        if(jTextFieldUsuario.getText().equals("admin")&&jPasswordFieldSenha.getText().equals("admin")){
        
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
          }
        
        else if(jTextFieldUsuario.getText().equals("") || jPasswordFieldSenha.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        
        else {
            int login = 0;
            for(Usuario e: lista.getGrupo()){
                if(e instanceof Cliente && ((Cliente) e).getNome().equals(jTextFieldUsuario.getText()) && ((Cliente) e).getSenha().equals(jPasswordFieldSenha.getText())){
                    TelaCliente tela = new TelaCliente();
                    tela.setVisible(true);
                    login=1;
                    dispose();
                }else
                if(e instanceof Admin && ((Admin) e).getNome().equals(jTextFieldUsuario.getText()) && ((Admin) e).getSenha().equals(jPasswordFieldSenha.getText())){
                    TelaPrincipal tela = new TelaPrincipal();
                    tela.setVisible(true);
                    login = 1;
                    dispose();
                }
            }
            if(login == 0){
                JOptionPane.showMessageDialog(null, "Dados Inválidos");
                jPasswordFieldSenha.setText("");
                jTextFieldUsuario.setText("");
            }
                
            
        }
        

    }//GEN-LAST:event_jButtonAcessoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAcessoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAcessoKeyPressed
       if(jTextFieldUsuario.getText().equals("admin")&&jPasswordFieldSenha.getText().equals("admin")){
        
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }else if(jTextFieldUsuario.getText().equals("gui")&&jPasswordFieldSenha.getText().equals("123")) {
    
    TelaCliente tel = new TelaCliente();
    tel.setVisible(true);
}else 
        JOptionPane.showMessageDialog(rootPane, "Usuário e Senha Inválidos!");
                                                

    }//GEN-LAST:event_jButtonAcessoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcesso;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelaLogin;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
