/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.*;
import controle.*;
import javax.swing.JOptionPane;
/**
 *
 * @author guilherme
 */
public class TelaCadRevista extends javax.swing.JFrame {

    Livraria livraria;
    /**
     * Creates new form TelaCadRevista
     */
    public TelaCadRevista() {
        
        livraria = new Livraria();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jLabelEditora = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCod = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jTextFieldEdit = new javax.swing.JTextField();
        Cadastrar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Revista");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setLayout(null);

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundodireitarevista.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 0, 100, 250);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(8, 60, 100, 270);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabelNome.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabelNome.setForeground(java.awt.Color.white);
        jLabelNome.setText("Nome:");
        jPanel2.add(jLabelNome);
        jLabelNome.setBounds(20, 30, 45, 22);

        jLabelCod.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabelCod.setForeground(java.awt.Color.white);
        jLabelCod.setText("Código:");
        jPanel2.add(jLabelCod);
        jLabelCod.setBounds(20, 80, 63, 22);

        jLabelPreco.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabelPreco.setForeground(java.awt.Color.white);
        jLabelPreco.setText("Preço:");
        jPanel2.add(jLabelPreco);
        jLabelPreco.setBounds(20, 130, 54, 22);

        jLabelEditora.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabelEditora.setForeground(java.awt.Color.white);
        jLabelEditora.setText("Editora:");
        jPanel2.add(jLabelEditora);
        jLabelEditora.setBounds(20, 180, 90, 22);
        jPanel2.add(jTextFieldNome);
        jTextFieldNome.setBounds(100, 30, 130, 28);
        jPanel2.add(jTextFieldCod);
        jTextFieldCod.setBounds(100, 80, 130, 28);
        jPanel2.add(jTextFieldPreco);
        jTextFieldPreco.setBounds(100, 130, 130, 28);

        jTextFieldEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEdit);
        jTextFieldEdit.setBounds(100, 180, 130, 28);

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(Cadastrar);
        Cadastrar.setBounds(20, 230, 100, 30);

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        jPanel2.add(Limpar);
        Limpar.setBounds(140, 230, 90, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoprinci_rev.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 260, 270);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(120, 50, 260, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/titulorev.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 60, 36);

        jLabel2.setFont(new java.awt.Font("TlwgMono", 1, 15)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Cadastrar Revista");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 20, 170, 22);

        jButton1.setFont(new java.awt.Font("TlwgMono", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow_left.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 10, 90, 30);

        setSize(new java.awt.Dimension(410, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        String nome = jTextFieldNome.getText();
        int cod = Integer.parseInt(jTextFieldCod.getText());
        double preco = Double.parseDouble(jTextFieldPreco.getText());
        String editora = jTextFieldEdit.getText();
        
        livraria.adquirirRevista(nome, cod, preco, editora, 2);
        try {
            ControleArquivo.salvaArquivo(livraria);
            JOptionPane.showMessageDialog(null, "Revista Cadastrado com Sucesso!");
            jTextFieldNome.setText("");
            jTextFieldCod.setText("");
            jTextFieldPreco.setText("");
            jTextFieldEdit.setText("");
        } 
        
        catch (IOException ex) {
            Logger.getLogger(TelaCadLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       TelaPrincipal tela = new TelaPrincipal();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
      jTextFieldNome.setText("");
      jTextFieldCod.setText("");
      jTextFieldPreco.setText("");
      jTextFieldEdit.setText("");
      
    }//GEN-LAST:event_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadRevista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Limpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelEditora;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldEdit;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPreco;
    // End of variables declaration//GEN-END:variables
}
