/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Item;
import modelo.Livraria;
import modelo.Livro;
import controle.*;

/**
 *
 * @author guylh
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    Livraria li = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        try {
            li = ControleArquivo.recuperarLivraria();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInterno = new javax.swing.JPanel();
        jLabelCadastro = new javax.swing.JLabel();
        jButtonCadLivro = new javax.swing.JButton();
        jButtonCadUsua = new javax.swing.JButton();
        jLabelTextoListar = new javax.swing.JLabel();
        jTextPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelInterno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelSistema = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTelaFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCadLivro = new javax.swing.JMenuItem();
        jMenuListLivro = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(570, 410));
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, null));
        jInternalFrameBemVindo.setTitle("Bem-Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInterno.setLayout(null);

        jLabelCadastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadastro.setText("Cadastros:");
        jPanelInterno.add(jLabelCadastro);
        jLabelCadastro.setBounds(10, 20, 90, 15);

        jButtonCadLivro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadlivro (2).png"))); // NOI18N
        jButtonCadLivro.setToolTipText("Cadastro de Livros");
        jButtonCadLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadLivroActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonCadLivro);
        jButtonCadLivro.setBounds(10, 40, 75, 75);

        jButtonCadUsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadusuario-.png"))); // NOI18N
        jButtonCadUsua.setToolTipText("Cadastro de Usuário");
        jButtonCadUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuaActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonCadUsua);
        jButtonCadUsua.setBounds(100, 40, 75, 75);

        jLabelTextoListar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelTextoListar.setText("Pesquisar Livro:");
        jPanelInterno.add(jLabelTextoListar);
        jLabelTextoListar.setBounds(220, 20, 120, 20);
        jPanelInterno.add(jTextPesquisar);
        jTextPesquisar.setBounds(220, 40, 250, 20);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/procurar.png"))); // NOI18N
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(220, 80, 33, 9);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/revista.png"))); // NOI18N
        jButton3.setToolTipText("Cadastrar Revista");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButton3);
        jButton3.setBounds(50, 130, 75, 75);

        jLabelInterno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundointer.png"))); // NOI18N
        jPanelInterno.add(jLabelInterno);
        jLabelInterno.setBounds(0, 0, 500, 230);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanelInterno.add(jScrollPane1);
        jScrollPane1.setBounds(0, 150, 510, 160);

        jInternalFrameBemVindo.getContentPane().add(jPanelInterno);
        jPanelInterno.setBounds(0, 40, 540, 230);

        jLabelSistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSistema.setText("Sistema de Gerenciamento: ");
        jInternalFrameBemVindo.getContentPane().add(jLabelSistema);
        jLabelSistema.setBounds(30, 10, 230, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cog.png"))); // NOI18N
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 49, 18);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(30, 50, 500, 300);

        jLabelTelaFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telaprinc.png"))); // NOI18N
        getContentPane().add(jLabelTelaFundoPrincipal);
        jLabelTelaFundoPrincipal.setBounds(0, -10, 570, 410);

        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.png"))); // NOI18N
        jMenuCadastro.setText("Livros");

        jMenuCadLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_add.png"))); // NOI18N
        jMenuCadLivro.setText("Adicionar");
        jMenuCadLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadLivroActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadLivro);

        jMenuListLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_edit.png"))); // NOI18N
        jMenuListLivro.setText("Listar");
        jMenuCadastro.add(jMenuListLivro);

        jMenuBar1.add(jMenuCadastro);

        jMenuListar.setBackground(new java.awt.Color(153, 153, 153));
        jMenuListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        jMenuListar.setText("Usuários");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_add.png"))); // NOI18N
        jMenuItem2.setText("Adicionar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_edit.png"))); // NOI18N
        jMenuItem3.setText("Listar");
        jMenuListar.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_delete.png"))); // NOI18N
        jMenuItem4.setText("Excluir");
        jMenuListar.add(jMenuItem4);

        jMenuBar1.add(jMenuListar);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cog.png"))); // NOI18N
        jMenu1.setText("Ferramentas");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house.png"))); // NOI18N
        jMenuItem1.setText("Tela Inical");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenuSobreMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSobre);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuSairMouseExited(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(552, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadLivroActionPerformed
       TelaCadLivro tela = new TelaCadLivro();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonCadLivroActionPerformed

    private void jButtonCadUsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuaActionPerformed
         TelaCadUsuario tela = new TelaCadUsuario();
        tela.setVisible(true);
         dispose();
    }//GEN-LAST:event_jButtonCadUsuaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuCadLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadLivroActionPerformed
        TelaCadLivro tela = new TelaCadLivro();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenuCadLivroActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
          TelaLogin tela = new TelaLogin();
           tela.setVisible(true);
           dispose();
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseExited
    
    }//GEN-LAST:event_jMenuSairMouseExited

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaCadUsuario tela = new TelaCadUsuario();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuSobreMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuSobreMenuKeyPressed
       
    }//GEN-LAST:event_jMenuSobreMenuKeyPressed

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        JOptionPane.showMessageDialog(null, "Um Sistema Novo e intuitivo, facil e pratico de se utilizar o SisLivr é uma moderna ferramnete de gerenciamneto de sua livraria!");
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        int achou = 0;
        for(Item x:li.getAcervo()){
            if(x instanceof Livro && ((Livro) x).getTitulo().equals(jTextPesquisar.getText())){
                JOptionPane.showMessageDialog(null, "Livro encontrado");
                achou = 1;
            }
        }
        
        if(achou == 0)
            JOptionPane.showMessageDialog(null, "Nao achou");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TelaCadRevista tela = new TelaCadRevista();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCadLivro;
    private javax.swing.JButton jButtonCadUsua;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelInterno;
    private javax.swing.JLabel jLabelSistema;
    private javax.swing.JLabel jLabelTelaFundoPrincipal;
    private javax.swing.JLabel jLabelTextoListar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadLivro;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuListLivro;
    private javax.swing.JMenu jMenuListar;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanelInterno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextPesquisar;
    // End of variables declaration//GEN-END:variables
}
